# Generated by Django 5.1.2 on 2024-10-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_starter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='price',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
            preserve_default=False,
        ),
    ]
